volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.dev
    depends_on:
      - database
      - cache
  
  frontend:
    build: ./frontend/racktrack-frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data